version: '3.8'

services:
  odontoprevjava:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - oracle-db
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  oracle-db:
    image: oracleinanutshell/oracle-xe-11g:latest
    ports:
      - "1521:1521"
    environment:
      ORACLE_ALLOW_REMOTE: "true"
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
    volumes:
      - oracle-data:/u01/app/oracle
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

networks:
  app-network:
    driver: bridge

volumes:
  oracle-data:
